language: ruby

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0

bundler_args: --without darwin

notifications:
  email: false

before_script:
  # Install treat language
  - bundle exec rake language

script: bundle exec rspec spec
